.TH feh-cam 1 "29 Oct 2000" "feh-cam"
.SH NAME
.HP
feh-cam - a utility for viewing live webcam images
.HP
gen-cam-menu - a utility for updating Enlightenment user 
menus for feh-cam.
.SH SYNOPSIS
.HP
feh-cam [options]
.P
.SH DESCRIPTION
.HP
.I feh-cam
is a Perl wrapper for feh that simplifies viewing webcams.
feh-cam uses keyed bookmarks. It helps manage viewing your
favorite webcam sites with feh.
.HP
.I gen-cam-menu
is a shell script that creates Enlightenment user menu entries
in $HOME/.enlightenment/.
.HP
Type
.I "feh-cam -h"
at a command line for usage information.
.P
.SH AUTHORS
This manual page was written by <unknown> for the Debian project.
.SH SEE ALSO
.HP
feh(1)
