/* newkeyev.h 

* June 2012 Note:  This header is autogenerated by 
*    feh_init.c -DFIRST_PASS 
*
* Please read feh_init.h for the "why" of it all.
*
* ANY CHANGES MADE TO THIS FILE WILL BE LOST !
*
*/

#ifndef NEWKEYEV_H
#define NEWKEYEV_H



/* stub_function prototypes for newkeyev.c */

void stub_action_0( void );
void stub_action_1( void );
void stub_action_2( void );
void stub_action_3( void );
void stub_action_4( void );
void stub_action_5( void );
void stub_action_6( void );
void stub_action_7( void );
void stub_action_8( void );
void stub_action_9( void );
void stub_add2move_list( void );
void stub_close( void );
void stub_delete( void );
void stub_enter_move_mode( void );
void stub_flip( void );
void stub_help4bindings( void );
void stub_help4feh( void );
void stub_jump_back( void );
void stub_jump_first( void );
void stub_jump_fwd( void );
void stub_jump_last( void );
void stub_jump_random( void );
void stub_jump_to_10( void );
void stub_jump_to_100( void );
void stub_jump_to_20( void );
void stub_jump_to_30( void );
void stub_jump_to_40( void );
void stub_jump_to_50( void );
void stub_jump_to_60( void );
void stub_jump_to_70( void );
void stub_jump_to_80( void );
void stub_jump_to_90( void );
void stub_menu_child( void );
void stub_menu_close( void );
void stub_menu_down( void );
void stub_menu_parent( void );
void stub_menu_select( void );
void stub_menu_up( void );
void stub_mirror( void );
void stub_move_cancel( void );
void stub_move_dropit( void );
void stub_move_flip_list( void );
void stub_move_help( void );
void stub_move_one_bak( void );
void stub_move_one_fwd( void );
void stub_move_ret2pos( void );
void stub_move_to_10( void );
void stub_move_to_20( void );
void stub_move_to_30( void );
void stub_move_to_40( void );
void stub_move_to_50( void );
void stub_move_to_60( void );
void stub_move_to_70( void );
void stub_move_to_80( void );
void stub_move_to_90( void );
void stub_move_to_beg( void );
void stub_move_to_end( void );
void stub_next_img( void );
void stub_orient_1( void );
void stub_orient_3( void );
void stub_prev_img( void );
void stub_quit( void );
void stub_reload_image( void );
void stub_reload_minus( void );
void stub_reload_plus( void );
void stub_remove( void );
void stub_render( void );
void stub_ret2pos( void );
void stub_ret2posFwd( void );
void stub_rot_ccw_fast( void );
void stub_rot_ccw_slow( void );
void stub_rot_cw_fast( void );
void stub_rot_cw_slow( void );
void stub_save_filelist( void );
void stub_save_image( void );
void stub_scroll_down( void );
void stub_scroll_down_page( void );
void stub_scroll_left( void );
void stub_scroll_left_page( void );
void stub_scroll_right( void );
void stub_scroll_right_page( void );
void stub_scroll_up( void );
void stub_scroll_up_page( void );
void stub_size_to_image( void );
void stub_toggle_actions( void );
void stub_toggle_aliasing( void );
void stub_toggle_caption( void );
void stub_toggle_filenames( void );
void stub_toggle_fullscreen( void );
void stub_toggle_info( void );
void stub_toggle_menu( void );
void stub_toggle_pause( void );
void stub_toggle_pointer( void );
void stub_toggle_thumb_mode( void );
void stub_zoom_default( void );
void stub_zoom_fit( void );
void stub_zoom_in( void );
void stub_zoom_out( void );

/* List of all actions ReMapped to other functions...        */
/*           jump_to_10 ==> stub_move_to_10                  */
/*           jump_to_20 ==> stub_move_to_20                  */
/*           jump_to_30 ==> stub_move_to_30                  */
/*           jump_to_40 ==> stub_move_to_40                  */
/*           jump_to_50 ==> stub_move_to_50                  */
/*           jump_to_60 ==> stub_move_to_60                  */
/*           jump_to_70 ==> stub_move_to_70                  */
/*           jump_to_80 ==> stub_move_to_80                  */
/*           jump_to_90 ==> stub_move_to_90                  */
/*          jump_to_100 ==> stub_move_to_end                 */
/*              ret2pos ==> stub_move_ret2pos                */
/*            move_help ==> stub_help4bindings               */


 /* funcptr[] array is used by both feh_init.c and newkeyev.c */

StubPtr funcptr[] = { 
 &stub_action_0 ,
 &stub_action_1 ,
 &stub_action_2 ,
 &stub_action_3 ,
 &stub_action_4 ,
 &stub_action_5 ,
 &stub_action_6 ,
 &stub_action_7 ,
 &stub_action_8 ,
 &stub_action_9 ,
 &stub_add2move_list ,
 &stub_close ,
 &stub_delete ,
 &stub_enter_move_mode ,
 &stub_flip ,
 &stub_help4bindings ,
 &stub_help4feh ,
 &stub_jump_back ,
 &stub_jump_first ,
 &stub_jump_fwd ,
 &stub_jump_last ,
 &stub_jump_random ,
 &stub_move_to_10 ,    /* ReMapped*/
 &stub_move_to_end ,    /* ReMapped*/
 &stub_move_to_20 ,    /* ReMapped*/
 &stub_move_to_30 ,    /* ReMapped*/
 &stub_move_to_40 ,    /* ReMapped*/
 &stub_move_to_50 ,    /* ReMapped*/
 &stub_move_to_60 ,    /* ReMapped*/
 &stub_move_to_70 ,    /* ReMapped*/
 &stub_move_to_80 ,    /* ReMapped*/
 &stub_move_to_90 ,    /* ReMapped*/
 &stub_menu_child ,
 &stub_menu_close ,
 &stub_menu_down ,
 &stub_menu_parent ,
 &stub_menu_select ,
 &stub_menu_up ,
 &stub_mirror ,
 &stub_move_cancel ,
 &stub_move_dropit ,
 &stub_move_flip_list ,
 &stub_help4bindings ,    /* ReMapped*/
 &stub_move_one_bak ,
 &stub_move_one_fwd ,
 &stub_move_ret2pos ,
 &stub_move_to_10 ,
 &stub_move_to_20 ,
 &stub_move_to_30 ,
 &stub_move_to_40 ,
 &stub_move_to_50 ,
 &stub_move_to_60 ,
 &stub_move_to_70 ,
 &stub_move_to_80 ,
 &stub_move_to_90 ,
 &stub_move_to_beg ,
 &stub_move_to_end ,
 &stub_next_img ,
 &stub_orient_1 ,
 &stub_orient_3 ,
 &stub_prev_img ,
 &stub_quit ,
 &stub_reload_image ,
 &stub_reload_minus ,
 &stub_reload_plus ,
 &stub_remove ,
 &stub_render ,
 &stub_move_ret2pos ,    /* ReMapped*/
 &stub_ret2posFwd ,
 &stub_rot_ccw_fast ,
 &stub_rot_ccw_slow ,
 &stub_rot_cw_fast ,
 &stub_rot_cw_slow ,
 &stub_save_filelist ,
 &stub_save_image ,
 &stub_scroll_down ,
 &stub_scroll_down_page ,
 &stub_scroll_left ,
 &stub_scroll_left_page ,
 &stub_scroll_right ,
 &stub_scroll_right_page ,
 &stub_scroll_up ,
 &stub_scroll_up_page ,
 &stub_size_to_image ,
 &stub_toggle_actions ,
 &stub_toggle_aliasing ,
 &stub_toggle_caption ,
 &stub_toggle_filenames ,
 &stub_toggle_fullscreen ,
 &stub_toggle_info ,
 &stub_toggle_menu ,
 &stub_toggle_pause ,
 &stub_toggle_pointer ,
 &stub_toggle_thumb_mode ,
 &stub_zoom_default ,
 &stub_zoom_fit ,
 &stub_zoom_in ,
 &stub_zoom_out ,
};  /* end of funcptr[] */



#define DFLT_ACT_CNT    98


/* ############ EVERYTHING ABOVE IS AUTO GENNERATED ############# */ 

#endif    /* end of #ifdef  NEWKEYEV_H */
