/* stubptr.c - auto generated by feh_init.c */

/* TEST functions for ALL stub_actions() */


#include <stdio.h>

int stub_action_0(int i){ printf(" index is %d, <stub_action_0>\n",i); return ++i;};
int stub_action_1(int i){ printf(" index is %d, <stub_action_1>\n",i); return ++i;};
int stub_action_2(int i){ printf(" index is %d, <stub_action_2>\n",i); return ++i;};
int stub_action_3(int i){ printf(" index is %d, <stub_action_3>\n",i); return ++i;};
int stub_action_4(int i){ printf(" index is %d, <stub_action_4>\n",i); return ++i;};
int stub_action_5(int i){ printf(" index is %d, <stub_action_5>\n",i); return ++i;};
int stub_action_6(int i){ printf(" index is %d, <stub_action_6>\n",i); return ++i;};
int stub_action_7(int i){ printf(" index is %d, <stub_action_7>\n",i); return ++i;};
int stub_action_8(int i){ printf(" index is %d, <stub_action_8>\n",i); return ++i;};
int stub_action_9(int i){ printf(" index is %d, <stub_action_9>\n",i); return ++i;};
int stub_add2move_list(int i){ printf(" index is %d, <stub_add2move_list>\n",i); return ++i;};
int stub_close(int i){ printf(" index is %d, <stub_close>\n",i); return ++i;};
int stub_delete(int i){ printf(" index is %d, <stub_delete>\n",i); return ++i;};
int stub_enter_move_mode(int i){ printf(" index is %d, <stub_enter_move_mode>\n",i); return ++i;};
int stub_flip(int i){ printf(" index is %d, <stub_flip>\n",i); return ++i;};
int stub_help4bindings(int i){ printf(" index is %d, <stub_help4bindings>\n",i); return ++i;};
int stub_help4feh(int i){ printf(" index is %d, <stub_help4feh>\n",i); return ++i;};
int stub_jump_back(int i){ printf(" index is %d, <stub_jump_back>\n",i); return ++i;};
int stub_jump_first(int i){ printf(" index is %d, <stub_jump_first>\n",i); return ++i;};
int stub_jump_fwd(int i){ printf(" index is %d, <stub_jump_fwd>\n",i); return ++i;};
int stub_jump_last(int i){ printf(" index is %d, <stub_jump_last>\n",i); return ++i;};
int stub_jump_random(int i){ printf(" index is %d, <stub_jump_random>\n",i); return ++i;};
int stub_jump_to_10(int i){ printf(" index is %d, <stub_jump_to_10>\n",i); return ++i;};
int stub_jump_to_100(int i){ printf(" index is %d, <stub_jump_to_100>\n",i); return ++i;};
int stub_jump_to_20(int i){ printf(" index is %d, <stub_jump_to_20>\n",i); return ++i;};
int stub_jump_to_30(int i){ printf(" index is %d, <stub_jump_to_30>\n",i); return ++i;};
int stub_jump_to_40(int i){ printf(" index is %d, <stub_jump_to_40>\n",i); return ++i;};
int stub_jump_to_50(int i){ printf(" index is %d, <stub_jump_to_50>\n",i); return ++i;};
int stub_jump_to_60(int i){ printf(" index is %d, <stub_jump_to_60>\n",i); return ++i;};
int stub_jump_to_70(int i){ printf(" index is %d, <stub_jump_to_70>\n",i); return ++i;};
int stub_jump_to_80(int i){ printf(" index is %d, <stub_jump_to_80>\n",i); return ++i;};
int stub_jump_to_90(int i){ printf(" index is %d, <stub_jump_to_90>\n",i); return ++i;};
int stub_menu_child(int i){ printf(" index is %d, <stub_menu_child>\n",i); return ++i;};
int stub_menu_close(int i){ printf(" index is %d, <stub_menu_close>\n",i); return ++i;};
int stub_menu_down(int i){ printf(" index is %d, <stub_menu_down>\n",i); return ++i;};
int stub_menu_parent(int i){ printf(" index is %d, <stub_menu_parent>\n",i); return ++i;};
int stub_menu_select(int i){ printf(" index is %d, <stub_menu_select>\n",i); return ++i;};
int stub_menu_up(int i){ printf(" index is %d, <stub_menu_up>\n",i); return ++i;};
int stub_mirror(int i){ printf(" index is %d, <stub_mirror>\n",i); return ++i;};
int stub_move_cancel(int i){ printf(" index is %d, <stub_move_cancel>\n",i); return ++i;};
int stub_move_dropit(int i){ printf(" index is %d, <stub_move_dropit>\n",i); return ++i;};
int stub_move_flip_list(int i){ printf(" index is %d, <stub_move_flip_list>\n",i); return ++i;};
int stub_move_help(int i){ printf(" index is %d, <stub_move_help>\n",i); return ++i;};
int stub_move_one_bak(int i){ printf(" index is %d, <stub_move_one_bak>\n",i); return ++i;};
int stub_move_one_fwd(int i){ printf(" index is %d, <stub_move_one_fwd>\n",i); return ++i;};
int stub_move_ret2pos(int i){ printf(" index is %d, <stub_move_ret2pos>\n",i); return ++i;};
int stub_move_to_10(int i){ printf(" index is %d, <stub_move_to_10>\n",i); return ++i;};
int stub_move_to_20(int i){ printf(" index is %d, <stub_move_to_20>\n",i); return ++i;};
int stub_move_to_30(int i){ printf(" index is %d, <stub_move_to_30>\n",i); return ++i;};
int stub_move_to_40(int i){ printf(" index is %d, <stub_move_to_40>\n",i); return ++i;};
int stub_move_to_50(int i){ printf(" index is %d, <stub_move_to_50>\n",i); return ++i;};
int stub_move_to_60(int i){ printf(" index is %d, <stub_move_to_60>\n",i); return ++i;};
int stub_move_to_70(int i){ printf(" index is %d, <stub_move_to_70>\n",i); return ++i;};
int stub_move_to_80(int i){ printf(" index is %d, <stub_move_to_80>\n",i); return ++i;};
int stub_move_to_90(int i){ printf(" index is %d, <stub_move_to_90>\n",i); return ++i;};
int stub_move_to_beg(int i){ printf(" index is %d, <stub_move_to_beg>\n",i); return ++i;};
int stub_move_to_end(int i){ printf(" index is %d, <stub_move_to_end>\n",i); return ++i;};
int stub_next_img(int i){ printf(" index is %d, <stub_next_img>\n",i); return ++i;};
int stub_orient_1(int i){ printf(" index is %d, <stub_orient_1>\n",i); return ++i;};
int stub_orient_3(int i){ printf(" index is %d, <stub_orient_3>\n",i); return ++i;};
int stub_prev_img(int i){ printf(" index is %d, <stub_prev_img>\n",i); return ++i;};
int stub_quit(int i){ printf(" index is %d, <stub_quit>\n",i); return ++i;};
int stub_reload_image(int i){ printf(" index is %d, <stub_reload_image>\n",i); return ++i;};
int stub_reload_minus(int i){ printf(" index is %d, <stub_reload_minus>\n",i); return ++i;};
int stub_reload_plus(int i){ printf(" index is %d, <stub_reload_plus>\n",i); return ++i;};
int stub_remove(int i){ printf(" index is %d, <stub_remove>\n",i); return ++i;};
int stub_render(int i){ printf(" index is %d, <stub_render>\n",i); return ++i;};
int stub_ret2pos(int i){ printf(" index is %d, <stub_ret2pos>\n",i); return ++i;};
int stub_ret2posFwd(int i){ printf(" index is %d, <stub_ret2posFwd>\n",i); return ++i;};
int stub_rot_ccw_fast(int i){ printf(" index is %d, <stub_rot_ccw_fast>\n",i); return ++i;};
int stub_rot_ccw_slow(int i){ printf(" index is %d, <stub_rot_ccw_slow>\n",i); return ++i;};
int stub_rot_cw_fast(int i){ printf(" index is %d, <stub_rot_cw_fast>\n",i); return ++i;};
int stub_rot_cw_slow(int i){ printf(" index is %d, <stub_rot_cw_slow>\n",i); return ++i;};
int stub_save_filelist(int i){ printf(" index is %d, <stub_save_filelist>\n",i); return ++i;};
int stub_save_image(int i){ printf(" index is %d, <stub_save_image>\n",i); return ++i;};
int stub_scroll_down(int i){ printf(" index is %d, <stub_scroll_down>\n",i); return ++i;};
int stub_scroll_down_page(int i){ printf(" index is %d, <stub_scroll_down_page>\n",i); return ++i;};
int stub_scroll_left(int i){ printf(" index is %d, <stub_scroll_left>\n",i); return ++i;};
int stub_scroll_left_page(int i){ printf(" index is %d, <stub_scroll_left_page>\n",i); return ++i;};
int stub_scroll_right(int i){ printf(" index is %d, <stub_scroll_right>\n",i); return ++i;};
int stub_scroll_right_page(int i){ printf(" index is %d, <stub_scroll_right_page>\n",i); return ++i;};
int stub_scroll_up(int i){ printf(" index is %d, <stub_scroll_up>\n",i); return ++i;};
int stub_scroll_up_page(int i){ printf(" index is %d, <stub_scroll_up_page>\n",i); return ++i;};
int stub_size_to_image(int i){ printf(" index is %d, <stub_size_to_image>\n",i); return ++i;};
int stub_toggle_actions(int i){ printf(" index is %d, <stub_toggle_actions>\n",i); return ++i;};
int stub_toggle_aliasing(int i){ printf(" index is %d, <stub_toggle_aliasing>\n",i); return ++i;};
int stub_toggle_caption(int i){ printf(" index is %d, <stub_toggle_caption>\n",i); return ++i;};
int stub_toggle_filenames(int i){ printf(" index is %d, <stub_toggle_filenames>\n",i); return ++i;};
int stub_toggle_fullscreen(int i){ printf(" index is %d, <stub_toggle_fullscreen>\n",i); return ++i;};
int stub_toggle_info(int i){ printf(" index is %d, <stub_toggle_info>\n",i); return ++i;};
int stub_toggle_menu(int i){ printf(" index is %d, <stub_toggle_menu>\n",i); return ++i;};
int stub_toggle_pause(int i){ printf(" index is %d, <stub_toggle_pause>\n",i); return ++i;};
int stub_toggle_pointer(int i){ printf(" index is %d, <stub_toggle_pointer>\n",i); return ++i;};
int stub_toggle_thumb_mode(int i){ printf(" index is %d, <stub_toggle_thumb_mode>\n",i); return ++i;};
int stub_zoom_default(int i){ printf(" index is %d, <stub_zoom_default>\n",i); return ++i;};
int stub_zoom_fit(int i){ printf(" index is %d, <stub_zoom_fit>\n",i); return ++i;};
int stub_zoom_in(int i){ printf(" index is %d, <stub_zoom_in>\n",i); return ++i;};
int stub_zoom_out(int i){ printf(" index is %d, <stub_zoom_out>\n",i); return ++i;};

/* array that maps the action name to the index ( parallels funcptr[] ) */
typedef struct {
  char * action;
  int len;
} SimplePtrmap;

extern SimplePtrmap fname[];

SimplePtrmap fname[] = {
{ "action_0" , 8 } ,
{ "action_1" , 8 } ,
{ "action_2" , 8 } ,
{ "action_3" , 8 } ,
{ "action_4" , 8 } ,
{ "action_5" , 8 } ,
{ "action_6" , 8 } ,
{ "action_7" , 8 } ,
{ "action_8" , 8 } ,
{ "action_9" , 8 } ,
{ "add2move_list" , 13 } ,
{ "close" , 5 } ,
{ "delete" , 6 } ,
{ "enter_move_mode" , 15 } ,
{ "flip" , 4 } ,
{ "help4bindings" , 13 } ,
{ "help4feh" , 8 } ,
{ "jump_back" , 9 } ,
{ "jump_first" , 10 } ,
{ "jump_fwd" , 8 } ,
{ "jump_last" , 9 } ,
{ "jump_random" , 11 } ,
{ "jump_to_10" , 10 } ,
{ "jump_to_100" , 11 } ,
{ "jump_to_20" , 10 } ,
{ "jump_to_30" , 10 } ,
{ "jump_to_40" , 10 } ,
{ "jump_to_50" , 10 } ,
{ "jump_to_60" , 10 } ,
{ "jump_to_70" , 10 } ,
{ "jump_to_80" , 10 } ,
{ "jump_to_90" , 10 } ,
{ "menu_child" , 10 } ,
{ "menu_close" , 10 } ,
{ "menu_down" , 9 } ,
{ "menu_parent" , 11 } ,
{ "menu_select" , 11 } ,
{ "menu_up" , 7 } ,
{ "mirror" , 6 } ,
{ "move_cancel" , 11 } ,
{ "move_dropit" , 11 } ,
{ "move_flip_list" , 14 } ,
{ "move_help" , 9 } ,
{ "move_one_bak" , 12 } ,
{ "move_one_fwd" , 12 } ,
{ "move_ret2pos" , 12 } ,
{ "move_to_10" , 10 } ,
{ "move_to_20" , 10 } ,
{ "move_to_30" , 10 } ,
{ "move_to_40" , 10 } ,
{ "move_to_50" , 10 } ,
{ "move_to_60" , 10 } ,
{ "move_to_70" , 10 } ,
{ "move_to_80" , 10 } ,
{ "move_to_90" , 10 } ,
{ "move_to_beg" , 11 } ,
{ "move_to_end" , 11 } ,
{ "next_img" , 8 } ,
{ "orient_1" , 8 } ,
{ "orient_3" , 8 } ,
{ "prev_img" , 8 } ,
{ "quit" , 4 } ,
{ "reload_image" , 12 } ,
{ "reload_minus" , 12 } ,
{ "reload_plus" , 11 } ,
{ "remove" , 6 } ,
{ "render" , 6 } ,
{ "ret2pos" , 7 } ,
{ "ret2posFwd" , 10 } ,
{ "rot_ccw_fast" , 12 } ,
{ "rot_ccw_slow" , 12 } ,
{ "rot_cw_fast" , 11 } ,
{ "rot_cw_slow" , 11 } ,
{ "save_filelist" , 13 } ,
{ "save_image" , 10 } ,
{ "scroll_down" , 11 } ,
{ "scroll_down_page" , 16 } ,
{ "scroll_left" , 11 } ,
{ "scroll_left_page" , 16 } ,
{ "scroll_right" , 12 } ,
{ "scroll_right_page" , 17 } ,
{ "scroll_up" , 9 } ,
{ "scroll_up_page" , 14 } ,
{ "size_to_image" , 13 } ,
{ "toggle_actions" , 14 } ,
{ "toggle_aliasing" , 15 } ,
{ "toggle_caption" , 14 } ,
{ "toggle_filenames" , 16 } ,
{ "toggle_fullscreen" , 17 } ,
{ "toggle_info" , 11 } ,
{ "toggle_menu" , 11 } ,
{ "toggle_pause" , 12 } ,
{ "toggle_pointer" , 14 } ,
{ "toggle_thumb_mode" , 17 } ,
{ "zoom_default" , 12 } ,
{ "zoom_fit" , 8 } ,
{ "zoom_in" , 7 } ,
{ "zoom_out" , 8 } ,
};  /* end of fname[] */

int fname_cnt=98 ;

/* The rest of this is included in BOTH versions of feh_init */
/* List of all actions ReMapped to other functions...        */
/*           jump_to_10 ==> stub_move_to_10                  */
/*           jump_to_20 ==> stub_move_to_20                  */
/*           jump_to_30 ==> stub_move_to_30                  */
/*           jump_to_40 ==> stub_move_to_40                  */
/*           jump_to_50 ==> stub_move_to_50                  */
/*           jump_to_60 ==> stub_move_to_60                  */
/*           jump_to_70 ==> stub_move_to_70                  */
/*           jump_to_80 ==> stub_move_to_80                  */
/*           jump_to_90 ==> stub_move_to_90                  */
/*          jump_to_100 ==> stub_move_to_end                 */
/*              ret2pos ==> stub_move_ret2pos                */
/*            move_help ==> stub_help4bindings               */


 /* funcptr[] array is used by both feh_init.c and newkeyev.c */

typedef  int (*StubPtr)( int );      /* def for function pointer */



StubPtr funcptr[] = { 
 &stub_action_0 ,
 &stub_action_1 ,
 &stub_action_2 ,
 &stub_action_3 ,
 &stub_action_4 ,
 &stub_action_5 ,
 &stub_action_6 ,
 &stub_action_7 ,
 &stub_action_8 ,
 &stub_action_9 ,
 &stub_add2move_list ,
 &stub_close ,
 &stub_delete ,
 &stub_enter_move_mode ,
 &stub_flip ,
 &stub_help4bindings ,
 &stub_help4feh ,
 &stub_jump_back ,
 &stub_jump_first ,
 &stub_jump_fwd ,
 &stub_jump_last ,
 &stub_jump_random ,
 &stub_move_to_10 ,    /* ReMapped*/
 &stub_move_to_end ,    /* ReMapped*/
 &stub_move_to_20 ,    /* ReMapped*/
 &stub_move_to_30 ,    /* ReMapped*/
 &stub_move_to_40 ,    /* ReMapped*/
 &stub_move_to_50 ,    /* ReMapped*/
 &stub_move_to_60 ,    /* ReMapped*/
 &stub_move_to_70 ,    /* ReMapped*/
 &stub_move_to_80 ,    /* ReMapped*/
 &stub_move_to_90 ,    /* ReMapped*/
 &stub_menu_child ,
 &stub_menu_close ,
 &stub_menu_down ,
 &stub_menu_parent ,
 &stub_menu_select ,
 &stub_menu_up ,
 &stub_mirror ,
 &stub_move_cancel ,
 &stub_move_dropit ,
 &stub_move_flip_list ,
 &stub_help4bindings ,    /* ReMapped*/
 &stub_move_one_bak ,
 &stub_move_one_fwd ,
 &stub_move_ret2pos ,
 &stub_move_to_10 ,
 &stub_move_to_20 ,
 &stub_move_to_30 ,
 &stub_move_to_40 ,
 &stub_move_to_50 ,
 &stub_move_to_60 ,
 &stub_move_to_70 ,
 &stub_move_to_80 ,
 &stub_move_to_90 ,
 &stub_move_to_beg ,
 &stub_move_to_end ,
 &stub_next_img ,
 &stub_orient_1 ,
 &stub_orient_3 ,
 &stub_prev_img ,
 &stub_quit ,
 &stub_reload_image ,
 &stub_reload_minus ,
 &stub_reload_plus ,
 &stub_remove ,
 &stub_render ,
 &stub_move_ret2pos ,    /* ReMapped*/
 &stub_ret2posFwd ,
 &stub_rot_ccw_fast ,
 &stub_rot_ccw_slow ,
 &stub_rot_cw_fast ,
 &stub_rot_cw_slow ,
 &stub_save_filelist ,
 &stub_save_image ,
 &stub_scroll_down ,
 &stub_scroll_down_page ,
 &stub_scroll_left ,
 &stub_scroll_left_page ,
 &stub_scroll_right ,
 &stub_scroll_right_page ,
 &stub_scroll_up ,
 &stub_scroll_up_page ,
 &stub_size_to_image ,
 &stub_toggle_actions ,
 &stub_toggle_aliasing ,
 &stub_toggle_caption ,
 &stub_toggle_filenames ,
 &stub_toggle_fullscreen ,
 &stub_toggle_info ,
 &stub_toggle_menu ,
 &stub_toggle_pause ,
 &stub_toggle_pointer ,
 &stub_toggle_thumb_mode ,
 &stub_zoom_default ,
 &stub_zoom_fit ,
 &stub_zoom_in ,
 &stub_zoom_out ,
};  /* end of funcptr[] */



#define DFLT_ACT_CNT    98



void test_all_funcptr( void ){

   int i=0;

    for (i=0; i< DFLT_ACT_CNT ; i++ ) funcptr[i]( i );

}

/* ############ EVERYTHING ABOVE IS AUTO GENNERATED ############# */ 
